### ISSUE TITLE
To-Do before inviting everyone:

### ISSUE THREAD

**Issue by emilydolson** [alife-data-standards/alife-data-standards#4]
- [x] Flesh out draft phylogeny standard
- [x] Flesh out draft genome standard
- [x] Add draft list of standards we eventually want
- [x] Add example converters 
- [x] Figure out how to add web tools

**Comment by emilydolson** [comment]
Okay, looks looked we're ready to invite people!
